### ISSUE TITLE
Docker container is flaky on GitHub CI

### ISSUE THREAD

**Issue by madebr** [ps2dev/ps2dev#67] opened 2023-03-15 14:58 UTC
Hello,

We're using the ps2dev/ps2dev:latest container to do ci on SDL.
Since recently, I began to notice linking the test executables sometimes fails.
When re-running the job, it then succeeds.

Let's consider today's failed run:
- [attempt 1](https://github.com/libsdl-org/SDL/actions/runs/4427085780/attempts/1) failed
- [attempt 2](https://github.com/libsdl-org/SDL/actions/runs/4427085780/attempts/2) succeeded

Example failing link command, from [attempt 1](https://github.com/libsdl-org/SDL/actions/runs/4427085780/attempts/1):
```
ninja: job failed: : && /usr/local/ps2dev/ee/bin/mips64r5900el-ps2-elf-gcc -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ports/include -D_EE -DPS2 -D__PS2__ -O2 -G0 -O3 -DNDEBUG -T/usr/local/ps2dev/ps2sdk/ee/startup/linkfile -L/usr/local/ps2dev/ps2sdk/ee/lib -L/usr/local/ps2dev/gsKit/lib -L/usr/local/ps2dev/ps2sdk/ports/lib -Wl,-zmax-page-size=128 test/CMakeFiles/testpopup.dir/testpopup.c.obj -o test/testpopup  libSDL3_test.a  libSDL3.a  -lm  -lpatches  -lgskit  -ldmakit  -lps2_drivers && :
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: /usr/local/ps2dev/ps2sdk/ports/lib/libps2_drivers.a(init_ps2_fileXio_driver.o): in function `init_fileXio_driver':
(.text+0x6c): undefined reference to `fileXioInit'
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: /usr/local/ps2dev/ps2sdk/ports/lib/libps2_drivers.a(init_ps2_hdd_driver.o): in function `init_hdd_driver':
(.text+0xd8): undefined reference to `fileXioDevctl'
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: /usr/local/ps2dev/ps2sdk/ports/lib/libps2_drivers.a(mount_current_partition_ps2_hdd_driver.o): in function `mount_current_hdd_partition':
(.text+0x228): undefined reference to `fileXioMount'
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: /usr/local/ps2dev/ps2sdk/ports/lib/libps2_drivers.a(umount_hdd_partition_ps2_hdd_driver.o): in function `umount_hdd_partition':
(.text+0x68): undefined reference to `fileXioDevctl'
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: (.text+0x70): undefined reference to `fileXioUmount'
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: (.text+0x8c): undefined reference to `fileXioDevctl'
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: (.text+0xac): undefined reference to `fileXioDevctl'
collect2: error: ld returned 1 exit status
```

Same command as above, but it succeeds now. From [attempt 2](https://github.com/libsdl-org/SDL/actions/runs/4427085780/attempts/2)
```
: && /usr/local/ps2dev/ee/bin/mips64r5900el-ps2-elf-gcc -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ports/include -D_EE -DPS2 -D__PS2__ -O2 -G0 -O3 -DNDEBUG -T/usr/local/ps2dev/ps2sdk/ee/startup/linkfile -L/usr/local/ps2dev/ps2sdk/ee/lib -L/usr/local/ps2dev/gsKit/lib -L/usr/local/ps2dev/ps2sdk/ports/lib -Wl,-zmax-page-size=128 test/CMakeFiles/testpopup.dir/testpopup.c.obj -o test/testpopup  libSDL3_test.a  libSDL3.a  -lm  -lpatches  -lgskit  -ldmakit  -lps2_drivers && :
```

The link commands are identical so there's some non-deterministic behavior going on.

**Comment by AKuHAK** [comment] 2023-03-16 11:26
dont use parallel (or -j) option, run single core everything, otherwise you can face race condition errors like this

**Comment by fjtrujy** [comment] 2024-01-15 21:14
Sorry for joining late to the party.
@madebr I don’t know how you are suffering this issue, but it must be something wrong in the SDL workflow.
I’m the creator of the SDL2 port for PS2, most probably the issue is because workflow still fetch and compile Ps2_driver, this shouldn’t be needed anymore.
I will create a PR in SDL and we can check it there.

cheers

**Comment by fjtrujy** [comment] 2024-01-16 07:07
@madebr I’m going to close this PR, reopen it if still suffers some issues

**Closed by fjtrujy** 2024-01-16 07:07 UTC
