### ISSUE TITLE
Weird compiler names after build

### ISSUE THREAD

**Issue by mscofield0** [ps2dev/ps2dev#26] opened 2021-02-19 02:12 UTC
I've ran the build script, and it finished. But the `ee` compilers seem to be weirdly named (not ee-g++):
```bash
$ ls
mips64r5900el-ps2-elf-addr2line  mips64r5900el-ps2-elf-gcc         mips64r5900el-ps2-elf-gdb            mips64r5900el-ps2-elf-ranlib
mips64r5900el-ps2-elf-ar         mips64r5900el-ps2-elf-gcc-10.2.0  mips64r5900el-ps2-elf-gdb-add-index  mips64r5900el-ps2-elf-readelf
mips64r5900el-ps2-elf-as         mips64r5900el-ps2-elf-gcc-ar      mips64r5900el-ps2-elf-ld             mips64r5900el-ps2-elf-size
mips64r5900el-ps2-elf-c++        mips64r5900el-ps2-elf-gcc-nm      mips64r5900el-ps2-elf-ld.bfd         mips64r5900el-ps2-elf-strings
mips64r5900el-ps2-elf-c++filt    mips64r5900el-ps2-elf-gcc-ranlib  mips64r5900el-ps2-elf-lto-dump       mips64r5900el-ps2-elf-strip
mips64r5900el-ps2-elf-cpp        mips64r5900el-ps2-elf-gcov        mips64r5900el-ps2-elf-nm
mips64r5900el-ps2-elf-elfedit    mips64r5900el-ps2-elf-gcov-dump   mips64r5900el-ps2-elf-objcopy
mips64r5900el-ps2-elf-g++        mips64r5900el-ps2-elf-gcov-tool   mips64r5900el-ps2-elf-objdump
```

**Comment by AKuHAK** [comment] 2021-02-19 07:21
`ee-gcc` is weirdy naming and was not following GNU naming convention. Anyway naming can be changed, developers should not care about it, cause you nevere ever have eto call itdirectly. Never use in your code `ee-gcc` directly, use $(EE_CC) instead.

**Comment by fjtrujy** [comment] 2021-02-19 08:05
Closing issue, because that's not an issue is the expected behavior.

Thanks.

**Closed by fjtrujy** 2021-02-19 08:05 UTC

**Comment by mscofield0** [comment] 2021-02-20 16:36
> `ee-gcc` is weirdy naming and was not following GNU naming convention. Anyway naming can be changed, developers should not care about it, cause you never ever have to call it directly. Never use in your code `ee-gcc` directly, use $(EE_CC) instead.

Should `${EE_CC}` be set after running the scripts? Because it's not set for me. If it's not supposed to be, what do I set `${EE_CC}` to?

**Comment by AKuHAK** [comment] 2021-02-20 18:59
https://github.com/ps2dev/ps2sdk/blob/11500fe1dcec03592e71406cbd9d34b39aa52589/ee/debug/samples/helloworld/Makefile.sample#L24

**Comment by mscofield0** [comment] 2021-02-21 09:16
Huh, weird. I don't have a `ee/debug/` folder at all...
